[package]
name = "aosae"
version = "0.1.0"
edition = "2024"

[dependencies]
fundsp = "0.20.0"
hound = "3.5.1"
cpal = "0.15.3"
symphonia = "0.5.4"
anyhow = "1.0.98"
huffman-compress = "0.6.1"
rustfft = "6.3.0"
lz4_flex = "0.11.3"
